### ISSUE TITLE
I2Cを有効にしただけでは正常に動作しない(Jessie/Stretch)

### ISSUE THREAD

**Issue by PINTO0309** [mechatrax/slee-pi2#2]
「1.3 時刻の反映 」の手順の直前に下記実施必要。
$ sudo nano /boot/config.txt

※下記を最下行に入力して保存。(Ctrl + o → Ctrl + x)
core_freq=250

Raspberry Pi を再起動
$ sudo reboot

**Comment by m-honda** [comment]
core_freq=250 は [sleepi2-firmware](https://github.com/mechatrax/sleepi2-firmware) をインストールすると /boot/config.txt に追記されます。
問題が再現するか確認してもらえますか？

**Comment by PINTO0309** [comment]
問題点を記載していませんでした。
Stretchでのみ、起動時にsleepi2-utils のFATALエラーが必ず出ます。
ちなみに、こちらに記載の手順を踏んで最後までキッティングしていますので、sleepi2-firmware はインストール済み、かつ、core_freq = 250 は追記済みです。
問題は、core_freq = 250 が追記されないこと、ではなく、ほかの原因なのかもしれませんね。
依然、起動時にsleepi2-utils のFATALエラーが出て不安定ですが、いったんクローズします。
